[package]
name = "aber-core"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = { git = "https://github.com/Hedgehogo/chumsky.git", branch = "char_impl_for_grapheme" }
smallvec = "1"
num-traits = "0.2"
num = "0.4"

[dev-dependencies]
indoc = "2"
